-- migrate:up
CREATE TABLE
    users (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        email VARCHAR(255) NOT NULL UNIQUE,
        hashed_password TEXT NOT NULL,
        is_active BOOLEAN NOT NULL DEFAULT FALSE,
        is_verified BOOLEAN NOT NULL DEFAULT FALSE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE
    user_profiles (
        user_id INT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
        full_name VARCHAR(100) NULL,
        avatar_url TEXT NULL,
        bio TEXT NULL,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE
    user_action_tokens (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        user_id INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
        token_hash VARCHAR(64) UNIQUE NOT NULL,
        token_type VARCHAR(32) NOT NULL, -- 'email_verification', 'password_reset', 'email_change'
        payload JSONB NULL, -- e.g., {"new_email": "newuser@example.com"}
        expires_at TIMESTAMPTZ NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE
    IF NOT EXISTS refresh_tokens (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(255) NULL, -- custom session name
        user_id INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
        token_hash VARCHAR(64) UNIQUE NOT NULL,
        expires_at TIMESTAMPTZ NOT NULL,
        device_info VARCHAR(255) NULL, -- e.g., "Mozilla/5.0 (Macintosh; Intel Mac OS X...)"
        ip_address VARCHAR(45) NULL, -- IPv4 or IPv6 tracking
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE INDEX idx_user_action_tokens_hash_type ON user_action_tokens (token_hash, token_type);

CREATE INDEX idx_refresh_tokens_hash ON refresh_tokens (token_hash);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

-- migrate:down
DROP TABLE IF EXISTS refresh_tokens;

DROP TABLE IF EXISTS user_action_tokens;

DROP TABLE IF EXISTS user_profiles;

DROP TABLE IF EXISTS users;