apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-management-ingress
  namespace: user-management
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: user-management.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-management-svc
            port:
              number: 80