apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
  namespace: user-management
type: Opaque
stringData:
  APP_NAME: "User Management"
  BASE_URL: "http://user-management.local"
  DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
  ACCESS_TOKEN_EXPIRE_MINUTES: "15"
  REFRESH_TOKEN_EXPIRE_MINUTES: "43200"
  ACTION_TOKEN_EXPIRE_MINUTES: "5"
  JWT_SECRET_KEY: "f1af3df30cbb0b19232cdeee378edffb12dbc969b47d3f93de91998de10de302"
  JWT_ALGORITHM: "HS256"
  MAILTRAP_API_TOKEN: "8c1bd9dc42382fa7ddf7658817b3d00f"
  NO_REPLY_EMAIL: "hello@demomailtrap.co"
  ACTION_TOKEN_COOLDOWN_SECONDS: "60"